# Generated by Django 4.0.5 on 2022-06-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aviso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='Matricula_avi',
        ),
    ]
