# Generated by Django 4.0.5 on 2022-06-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0002_remove_imovel_valor_imo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='matricula_imo',
        ),
    ]
